# Generated by Django 2.1.7 on 2019-03-05 14:04

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('changed_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='a_sky',
            fields=[
                ('sky_basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.Basic')),
                ('name', models.CharField(max_length=50)),
                ('color', colorful.fields.RGBColorField(default='#6EBAA7')),
                ('visible', models.BooleanField(default=True)),
                ('radius', models.DecimalField(decimal_places=5, default=5000, max_digits=10)),
                ('opacity', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('theta_start', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('theta_length', models.DecimalField(decimal_places=2, default=180, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebVR.Project')),
            ],
            bases=('WebVR.basic',),
        ),
        migrations.CreateModel(
            name='animation',
            fields=[
                ('basic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.Basic')),
            ],
            bases=('WebVR.basic',),
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('pos_basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.Basic')),
                ('pos_x', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pos_y', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pos_z', models.DecimalField(decimal_places=2, default=-4, max_digits=5)),
            ],
            bases=('WebVR.basic',),
        ),
        migrations.CreateModel(
            name='rotation',
            fields=[
                ('rot_basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.Basic')),
                ('rot_x', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rot_y', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rot_z', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            bases=('WebVR.basic',),
        ),
        migrations.CreateModel(
            name='scale',
            fields=[
                ('sca_basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.Basic')),
                ('sca_x', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('sca_y', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('sca_z', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
            bases=('WebVR.basic',),
        ),
        migrations.CreateModel(
            name='shadow',
            fields=[
                ('sha_basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.Basic')),
                ('cast', models.BooleanField(default=False)),
                ('receive', models.BooleanField(default=False)),
            ],
            bases=('WebVR.basic',),
        ),
        migrations.CreateModel(
            name='a_box',
            fields=[
                ('scale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.scale')),
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.position')),
                ('rotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.rotation')),
                ('shadow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.shadow')),
                ('name', models.CharField(max_length=50)),
                ('color', colorful.fields.RGBColorField(default='#FF0000')),
                ('visible', models.BooleanField(default=True)),
                ('depth', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebVR.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=('WebVR.shadow', 'WebVR.rotation', 'WebVR.position', 'WebVR.scale'),
        ),
        migrations.CreateModel(
            name='a_circle',
            fields=[
                ('scale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.scale')),
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.position')),
                ('rotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.rotation')),
                ('shadow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.shadow')),
                ('name', models.CharField(max_length=50)),
                ('color', colorful.fields.RGBColorField(default='#FF0000')),
                ('visible', models.BooleanField(default=True)),
                ('radius', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=256, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, default=512, max_digits=5)),
                ('theta_length', models.DecimalField(decimal_places=2, default=360, max_digits=5)),
                ('theta_start', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebVR.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=('WebVR.shadow', 'WebVR.rotation', 'WebVR.position', 'WebVR.scale'),
        ),
        migrations.CreateModel(
            name='a_cone',
            fields=[
                ('scale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.scale')),
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.position')),
                ('rotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.rotation')),
                ('shadow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.shadow')),
                ('name', models.CharField(max_length=50)),
                ('color', colorful.fields.RGBColorField(default='#FF0000')),
                ('visible', models.BooleanField(default=True)),
                ('radius_bottom', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('radius_top', models.DecimalField(decimal_places=2, default=0.8, max_digits=5)),
                ('theta_length', models.DecimalField(decimal_places=2, default=360, max_digits=5)),
                ('theta_start', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, default=512, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=256, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebVR.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=('WebVR.shadow', 'WebVR.rotation', 'WebVR.position', 'WebVR.scale'),
        ),
        migrations.CreateModel(
            name='a_cylinder',
            fields=[
                ('scale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.scale')),
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.position')),
                ('rotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.rotation')),
                ('shadow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.shadow')),
                ('name', models.CharField(max_length=50)),
                ('color', colorful.fields.RGBColorField(default='#FF0000')),
                ('visible', models.BooleanField(default=True)),
                ('radius', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('theta_length', models.DecimalField(decimal_places=2, default=360, max_digits=5)),
                ('theta_start', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, default=512, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('open_ended', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebVR.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=('WebVR.shadow', 'WebVR.rotation', 'WebVR.position', 'WebVR.scale'),
        ),
        migrations.CreateModel(
            name='a_dodecahedron',
            fields=[
                ('scale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.scale')),
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.position')),
                ('rotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.rotation')),
                ('shadow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.shadow')),
                ('name', models.CharField(max_length=50)),
                ('color', colorful.fields.RGBColorField(default='#FF0000')),
                ('visible', models.BooleanField(default=True)),
                ('radius', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebVR.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=('WebVR.shadow', 'WebVR.rotation', 'WebVR.position', 'WebVR.scale'),
        ),
        migrations.CreateModel(
            name='a_sphere',
            fields=[
                ('scale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.scale')),
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.position')),
                ('rotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.rotation')),
                ('shadow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.shadow')),
                ('name', models.CharField(max_length=50)),
                ('color', colorful.fields.RGBColorField(default='#FF0000')),
                ('visible', models.BooleanField(default=True)),
                ('height', models.DecimalField(decimal_places=2, default=256, max_digits=5)),
                ('radius', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('theta_length', models.DecimalField(decimal_places=2, default=180, max_digits=5)),
                ('theta_start', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, default=512, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebVR.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=('WebVR.shadow', 'WebVR.rotation', 'WebVR.position', 'WebVR.scale'),
        ),
    ]
