# Generated by Django 2.1.7 on 2019-03-02 16:30

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_box',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000'),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000'),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000'),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000'),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000'),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000'),
        ),
    ]
