# Generated by Django 2.1.7 on 2019-05-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_box',
            name='position_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_box',
            name='position_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_box',
            name='position_z',
            field=models.DecimalField(decimal_places=1, default=-4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_box',
            name='rotation_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_box',
            name='rotation_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_box',
            name='rotation_z',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_box',
            name='scale_x',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_box',
            name='scale_y',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_box',
            name='scale_z',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='position_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='position_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='position_z',
            field=models.DecimalField(decimal_places=1, default=-4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='rotation_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='rotation_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='rotation_z',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='scale_x',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='scale_y',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='scale_z',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='position_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='position_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='position_z',
            field=models.DecimalField(decimal_places=1, default=-4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='rotation_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='rotation_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='rotation_z',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='scale_x',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='scale_y',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='scale_z',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='position_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='position_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='position_z',
            field=models.DecimalField(decimal_places=1, default=-4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='rotation_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='rotation_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='rotation_z',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='scale_x',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='scale_y',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='scale_z',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='position_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='position_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='position_z',
            field=models.DecimalField(decimal_places=1, default=-4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='rotation_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='rotation_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='rotation_z',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='scale_x',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='scale_y',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='scale_z',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_icosahedron',
            name='position_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_icosahedron',
            name='position_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_icosahedron',
            name='position_z',
            field=models.DecimalField(decimal_places=1, default=-4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_icosahedron',
            name='rotation_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_icosahedron',
            name='rotation_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_icosahedron',
            name='rotation_z',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_icosahedron',
            name='scale_x',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_icosahedron',
            name='scale_y',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_icosahedron',
            name='scale_z',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_plane',
            name='position_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_plane',
            name='position_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_plane',
            name='position_z',
            field=models.DecimalField(decimal_places=1, default=-4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_plane',
            name='rotation_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_plane',
            name='rotation_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_plane',
            name='rotation_z',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_plane',
            name='scale_x',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_plane',
            name='scale_y',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_plane',
            name='scale_z',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='position_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='position_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='position_z',
            field=models.DecimalField(decimal_places=1, default=-4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='rotation_x',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='rotation_y',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='rotation_z',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='scale_x',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='scale_y',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='scale_z',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
    ]
