# Generated by Django 2.1.7 on 2019-03-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0002_auto_20190302_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_box',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_box',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_box',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='height',
            field=models.DecimalField(decimal_places=2, default=256, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='theta_length',
            field=models.DecimalField(decimal_places=2, default=360, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='theta_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='width',
            field=models.DecimalField(decimal_places=2, default=512, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='height',
            field=models.DecimalField(decimal_places=2, default=256, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='radius_bottom',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='radius_top',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='theta_length',
            field=models.DecimalField(decimal_places=2, default=360, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='theta_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='width',
            field=models.DecimalField(decimal_places=2, default=512, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='height',
            field=models.DecimalField(decimal_places=2, default=256, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='radius_bottom',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='radius_top',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='theta_length',
            field=models.DecimalField(decimal_places=2, default=360, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='theta_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='width',
            field=models.DecimalField(decimal_places=2, default=512, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='height',
            field=models.DecimalField(decimal_places=2, default=256, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='theta_length',
            field=models.DecimalField(decimal_places=2, default=180, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='theta_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='width',
            field=models.DecimalField(decimal_places=2, default=512, max_digits=5),
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='rot_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='rot_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='rot_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='scale',
            name='sca_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='scale',
            name='sca_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='scale',
            name='sca_z',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
