# Generated by Django 2.1.7 on 2019-02-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0003_auto_20190225_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_box',
            name='depth',
            field=models.FloatField(default=1),
        ),
    ]
