# Generated by Django 2.1.7 on 2019-04-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0003_auto_20190429_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_box',
            name='position',
        ),
        migrations.RemoveField(
            model_name='a_box',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='a_box',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='a_circle',
            name='position',
        ),
        migrations.RemoveField(
            model_name='a_circle',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='a_circle',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='a_cone',
            name='position',
        ),
        migrations.RemoveField(
            model_name='a_cone',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='a_cone',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='a_cylinder',
            name='position',
        ),
        migrations.RemoveField(
            model_name='a_cylinder',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='a_cylinder',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='a_dodecahedron',
            name='position',
        ),
        migrations.RemoveField(
            model_name='a_dodecahedron',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='a_dodecahedron',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='a_icosahedron',
            name='position',
        ),
        migrations.RemoveField(
            model_name='a_icosahedron',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='a_icosahedron',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='a_plane',
            name='position',
        ),
        migrations.RemoveField(
            model_name='a_plane',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='a_plane',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='a_sphere',
            name='position',
        ),
        migrations.RemoveField(
            model_name='a_sphere',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='a_sphere',
            name='scale',
        ),
        migrations.AddField(
            model_name='a_box',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_box',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_box',
            name='position_z',
            field=models.DecimalField(decimal_places=2, default=-4, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_box',
            name='rotation_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_box',
            name='rotation_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_box',
            name='rotation_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_box',
            name='scale_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_box',
            name='scale_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_box',
            name='scale_z',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_circle',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_circle',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_circle',
            name='position_z',
            field=models.DecimalField(decimal_places=2, default=-4, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_circle',
            name='rotation_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_circle',
            name='rotation_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_circle',
            name='rotation_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_circle',
            name='scale_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_circle',
            name='scale_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_circle',
            name='scale_z',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cone',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cone',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cone',
            name='position_z',
            field=models.DecimalField(decimal_places=2, default=-4, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cone',
            name='rotation_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cone',
            name='rotation_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cone',
            name='rotation_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cone',
            name='scale_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cone',
            name='scale_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cone',
            name='scale_z',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cylinder',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cylinder',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cylinder',
            name='position_z',
            field=models.DecimalField(decimal_places=2, default=-4, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cylinder',
            name='rotation_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cylinder',
            name='rotation_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cylinder',
            name='rotation_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cylinder',
            name='scale_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cylinder',
            name='scale_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_cylinder',
            name='scale_z',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_dodecahedron',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_dodecahedron',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_dodecahedron',
            name='position_z',
            field=models.DecimalField(decimal_places=2, default=-4, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_dodecahedron',
            name='rotation_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_dodecahedron',
            name='rotation_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_dodecahedron',
            name='rotation_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_dodecahedron',
            name='scale_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_dodecahedron',
            name='scale_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_dodecahedron',
            name='scale_z',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_icosahedron',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_icosahedron',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_icosahedron',
            name='position_z',
            field=models.DecimalField(decimal_places=2, default=-4, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_icosahedron',
            name='rotation_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_icosahedron',
            name='rotation_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_icosahedron',
            name='rotation_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_icosahedron',
            name='scale_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_icosahedron',
            name='scale_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_icosahedron',
            name='scale_z',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_plane',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_plane',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_plane',
            name='position_z',
            field=models.DecimalField(decimal_places=2, default=-4, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_plane',
            name='rotation_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_plane',
            name='rotation_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_plane',
            name='rotation_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_plane',
            name='scale_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_plane',
            name='scale_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_plane',
            name='scale_z',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_sphere',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_sphere',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_sphere',
            name='position_z',
            field=models.DecimalField(decimal_places=2, default=-4, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_sphere',
            name='rotation_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_sphere',
            name='rotation_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_sphere',
            name='rotation_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_sphere',
            name='scale_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_sphere',
            name='scale_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_sphere',
            name='scale_z',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
