# Generated by Django 2.1.7 on 2019-03-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0004_auto_20190302_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_box',
            name='src',
        ),
        migrations.RemoveField(
            model_name='a_circle',
            name='src',
        ),
        migrations.RemoveField(
            model_name='a_cone',
            name='src',
        ),
        migrations.RemoveField(
            model_name='a_cylinder',
            name='src',
        ),
        migrations.RemoveField(
            model_name='a_dodecahedron',
            name='src',
        ),
        migrations.RemoveField(
            model_name='a_sphere',
            name='src',
        ),
        migrations.AlterField(
            model_name='a_box',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='a_circle',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='a_cone',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='a_cylinder',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='a_dodecahedron',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='a_sphere',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
