# Generated by Django 2.1.7 on 2019-02-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0004_a_box_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_box',
            name='age',
        ),
        migrations.AddField(
            model_name='a_box',
            name='height',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='a_box',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='a_box',
            name='width',
            field=models.FloatField(default=1),
        ),
    ]
