# Generated by Django 2.1.7 on 2019-03-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0005_auto_20190304_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_cylinder',
            name='radius_bottom',
        ),
        migrations.RemoveField(
            model_name='a_cylinder',
            name='radius_top',
        ),
        migrations.AddField(
            model_name='a_cylinder',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='a_dodecahedron',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_z',
            field=models.DecimalField(decimal_places=2, default=-4, max_digits=5),
        ),
    ]
