# Generated by Django 2.1.7 on 2019-02-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0005_auto_20190225_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_box',
            name='home_group',
        ),
        migrations.AddField(
            model_name='a_box',
            name='src',
            field=models.TextField(default='any src'),
        ),
    ]
