# Generated by Django 2.1.7 on 2019-03-04 14:43

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0006_auto_20190304_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_sky',
            fields=[
                ('scale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.scale')),
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.position')),
                ('rotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.rotation')),
                ('shadow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.shadow')),
                ('name', models.CharField(max_length=50)),
                ('color', colorful.fields.RGBColorField(default='#FF0000')),
                ('visible', models.BooleanField(default=True)),
                ('radius', models.DecimalField(decimal_places=2, default=5000, max_digits=5)),
                ('opacity', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('theta_start', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('theta_length', models.DecimalField(decimal_places=2, default=180, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebVR.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=('WebVR.shadow', 'WebVR.rotation', 'WebVR.position', 'WebVR.scale'),
        ),
    ]
