# Generated by Django 2.1.7 on 2019-02-28 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0006_auto_20190225_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='a_box',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.Piece')),
            ],
            bases=('WebVR.piece',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Book_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.Piece')),
            ],
            bases=('WebVR.piece',),
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.Article')),
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.Book')),
            ],
            bases=('WebVR.book', 'WebVR.article'),
        ),
        migrations.CreateModel(
            name='Something',
            fields=[
                ('bookreview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.BookReview')),
            ],
            bases=('WebVR.bookreview',),
        ),
    ]
