# Generated by Django 2.1.7 on 2019-03-04 16:48

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0007_a_sky'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_sky',
            name='position_ptr',
        ),
        migrations.RemoveField(
            model_name='a_sky',
            name='rotation_ptr',
        ),
        migrations.RemoveField(
            model_name='a_sky',
            name='scale_ptr',
        ),
        migrations.RemoveField(
            model_name='a_sky',
            name='shadow_ptr',
        ),
        migrations.AddField(
            model_name='a_sky',
            name='sky_basic',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.Basic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='a_sky',
            name='color',
            field=colorful.fields.RGBColorField(default='#6EBAA7'),
        ),
    ]
