# Generated by Django 2.1.7 on 2019-02-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0008_a_box_a_circle_animation_basic_position_rotation_scale_shadow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_piece',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Book_piece',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='article_ptr',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='book_ptr',
        ),
        migrations.RemoveField(
            model_name='something',
            name='bookreview_ptr',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.DeleteModel(
            name='Something',
        ),
    ]
