# Generated by Django 2.1.7 on 2019-02-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0009_auto_20190228_0214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='a_box',
            new_name='abox',
        ),
        migrations.RenameModel(
            old_name='a_circle',
            new_name='acircle',
        ),
    ]
