# Generated by Django 2.1.7 on 2019-02-28 04:32

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebVR', '0011_auto_20190228_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_sphere',
            fields=[
                ('scale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.scale')),
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.position')),
                ('rotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='WebVR.rotation')),
                ('shadow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebVR.shadow')),
                ('name', models.CharField(max_length=50)),
                ('color', colorful.fields.RGBColorField(default=['#FF0000', '#00FF00', '#0000FF'])),
                ('src', models.TextField(default='')),
                ('visible', models.BooleanField(default=False)),
                ('height', models.FloatField(verbose_name=256)),
                ('radius', models.FloatField(verbose_name=1)),
                ('theta_length', models.FloatField(default=180)),
                ('theta_start', models.FloatField(default=0)),
                ('width', models.FloatField(default=512)),
            ],
            options={
                'abstract': False,
            },
            bases=('WebVR.shadow', 'WebVR.rotation', 'WebVR.position', 'WebVR.scale'),
        ),
    ]
